### ISSUE TITLE
jquery not bundled with webjea-1.1.157.7589

### ISSUE THREAD

**Issue by fr0mtheinternet** [markdomansky/WebJEA#54] opened 2021-06-18 07:35 UTC
3.5.1-min is referenced within default.aspx but isn't included within the scripts directory in the web root.

I discovered this after trying to enact the password-field hack in startup.js but found a bunch of 404 and reference errors.

Downloading the latest 3.6 release and updating default.aspx fixed this (though there's an unexpected token error for 'export', but everything appears ok).

**Comment by markdomansky** [comment] 2021-06-27 15:27
This is fixed in the next release.  Hopefully this will be released soon.

**Comment by kib** [comment] 2021-07-20 11:20
I think the export error you see in console is caused by the ESM version of popper being included. 
It can be fixed manually by overwriting both popper.js and popper.min.js (weird that both are there...) with the 1.16.1 UMD versions, for instance from https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js and https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.js

**Comment by markdomansky** [comment] 2021-08-01 16:59
Fixed with the latest release!

**Closed by markdomansky** 2021-08-01 16:59 UTC
Labels: bug
